### ISSUE TITLE
关于pretaining的问题

### ISSUE THREAD

**Issue by ShaofengZou** [Walleclipse/Deep_Speaker-speaker_recognition_system#10]

**Comment by Walleclipse** [comment]
你好！
你说的对，pretrain的网络就是给一段语音的特征，他能输出这段语音对应的说话人。
这个的作用就是pretrain的网络会在中间层特取声音的特征，而语音验证的网络也需要在中间层提取声音特征。所以我们可以把pretrain的网络的前面层（去掉softmax）拿过来用于语音验证的前面部分的模型。
在训练阶段，pretrain模型（speaker classification task）需要事先知道每一段语音的说话者。而语音验证（speaker recognition task）你不需要知道说话者是谁（换句话说是未知说话者），你只需要判断语音A是不是B发出的。

**Comment by ShaofengZou** [comment]
好滴，明白了，非常感谢！！

**Comment by Walleclipse** [comment]
不用客气
