### ISSUE TITLE
关于threshold问题

### ISSUE THREAD

**Issue by MichelleYang2017** [Walleclipse/Deep_Speaker-speaker_recognition_system#17]
您好，又来打扰您了，我看您在选择阈值的时候时从０到１之间选取的，理由是什么呢，相似度按理说不应该时在－１到１这个取值范围吗？

**Comment by Walleclipse** [comment]
我没有太明白你说的阈值是指什么？
cosine-smilarity的取值在 [-1,+1]这个范围内。triplet-loss的取值是大于0的。

**Comment by MichelleYang2017** [comment]
哦哦，谢谢．您代码里搜索我还有个问题问您．但我看见您的train_on_batch上ｙ为什么搞成随机的呢．

**Comment by MichelleYang2017** [comment]
谢谢
