### ISSUE TITLE
ask reason2

### ISSUE THREAD

**Issue by tingtingzhezhe** [Walleclipse/Deep_Speaker-speaker_recognition_system#19]
您好！我还是上次提问的学生，能得到您的回答很感激！
这次还想问一下对于原文百度文章中的实现，您的改进是什么？或者说和原文不同的是什么？为什么可以达到比原文还要好的效果？这个理论依据是？

**Comment by Walleclipse** [comment]
首先不能说达到了比原文更好的效果。因为我用的数据集和原文用的数据集完全不一样。说不定原文作者在这个数据集上能取得更好的成果。
相同点：模型与triplet-loss是相同的。(模型可能会有细微的区别)
不同点: 计算hard negative的方法不一样。原文利用大量gpu在大量的候选集中选择了最优样本。而我保存了历史的embedding信息。每次需要从历史embedding中选择最优样本。这大大减少了资源消耗量，但是可能会降低准确率（这点不能确定）
具体请查看[issue 4](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/issues/4#issuecomment-455841433) 和 [issue 11](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/issues/11#issue-414177207)

**Comment by tingtingzhezhe** [comment]
感谢感谢！！我也是实验后得到了不错的效果，想寻求一下理论依据，感谢您的帮助

**Comment by Hard-working-bee** [comment]
> 感谢感谢！！我也是实验后得到了不错的效果，想寻求一下理论依据，感谢您的帮助
我怎么显示一直在训练 没有终止
