### ISSUE TITLE
the problem when run pretraining.py

### ISSUE THREAD

**Issue by zhangshyang** [Walleclipse/Deep_Speaker-speaker_recognition_system#2]
In constants.py, I set the batch_size= 16. When run the pretraining.py, I always get the error which "tensorflow.python.framework.errors_impl.InvalidArgumentError: Inputs to operation training/Adam/gradients/AddN_2 of type _MklAddN must have the same size and shape.  Input 0: [983040] != input 1: [48,10,4,512]". Who know it and help me.

**Comment by Walleclipse** [comment]
1. You want to check the preprocessed data  audio/LibriSpeechSamples/train-clean-100-npy/*.npy  .and check the shape
2. I think this may caused by tensorflow and keras version incompatibility.I used  tensorflow-gpu==1.8.0
