### ISSUE TITLE
关于挑选样本

### ISSUE THREAD

**Issue by MichelleYang2017** [Walleclipse/Deep_Speaker-speaker_recognition_system#24]
你好，又来打扰您了，我发现到后期训练的时候的时候选样本的时间一次能达到１－２分钟，这个正常吗？感觉好慢啊

**Comment by Walleclipse** [comment]
这个估计也正常。因为挑选样本的时候，如果按照默认值，网络要前向传播 `CANDIDATES_PER_BATCH` = 640 个样本, 总共有 `HIST_TABLE_SIZE`=10 轮的历史数据，随后根据这 640*10=6400个样本中通过计算相似性选择一个batch的数据。这个还是挺耗时间的。当然另一部分耗时来与读入数据的io时间，你也可以检查一下io时间。 你想快一点，可以减少 `CANDIDATES_PER_BATCH` 或者`HIST_TABLE_SIZE` 。

**Comment by MichelleYang2017** [comment]
谢谢您
