### ISSUE TITLE
checkpoints/model_17200_0.54980.h5模型问题

### ISSUE THREAD

**Issue by liangyanfeng** [Walleclipse/Deep_Speaker-speaker_recognition_system#28]
你好， 请问 checkpoints/model_17200_0.54980.h5  这个模型是在什么情况下生成的？

在train-clean-100数据集直接用 select_batch 的triplet-loss进行训练, 得到的模型 大体在 7%， 是否 是因为 还没有训练完全？ 下面是训练过程的 summary:
 
![image](https://user-images.githubusercontent.com/2765208/57508785-1ab45e80-7335-11e9-8a8a-cad2f529aa2c.png)
![image](https://user-images.githubusercontent.com/2765208/57508808-2c960180-7335-11e9-81c0-64b0c6521d76.png)
![image](https://user-images.githubusercontent.com/2765208/57508822-391a5a00-7335-11e9-976a-17168677087e.png)
![image](https://user-images.githubusercontent.com/2765208/57508842-45061c00-7335-11e9-8716-46ae2d2379db.png)
![image](https://user-images.githubusercontent.com/2765208/57508857-4cc5c080-7335-11e9-98ad-68c7c9fd9b93.png)

训练过程中得到了 一个 best model : best_model53600_0.03806.h5
使用这个模型  在 test-clean 上测试 得到 EER = 7%~10%

在训练或者 测试过程中，我遗漏了什么 或者 还有 什么 tricks 的吗？ 期待你的回复，谢谢！

再次 感谢您上传如此优质的项目！

**Comment by Walleclipse** [comment]
0. 首先 best model 确实不是在测试集上表现最好的（这个很有可能有点过拟合到验证集），我的 5%的eer应该是某一步的ckpt。
1. 首先数据处理的时候 需要去除静音，不知道你做了没有? 如果你直接运行了` pre_process.py` 那么就去除了静音。
2. 我得到 5% 的eer应该是在 train-clean-100的基础上加了 train-clean-360 这个数据集，也就是说我数据更多。
3. 你可以试试先用 `pretraining.py` 进行预训练再用 triplet-loss 训练。
4. 多训练几轮

**Comment by liangyanfeng** [comment]
数据使用 pre_process.py 是去静音了， 训练集只用了train-clean-100；
加上 train-clean-360 我再跑一下，非常感谢你的回复！

**Comment by Fansgithub2019** [comment]
> 你好， 请问 checkpoints/model_17200_0.54980.h5 这个模型是在什么情况下生成的？
> 
> 在train-clean-100数据集直接用 select_batch 的triplet-loss进行训练, 得到的模型 大体在 7%， 是否 是因为 还没有训练完全？ 下面是训练过程的 summary:
> 
> ![image](https://user-images.githubusercontent.com/2765208/57508785-1ab45e80-7335-11e9-8a8a-cad2f529aa2c.png)
> ![image](https://user-images.githubusercontent.com/2765208/57508808-2c960180-7335-11e9-81c0-64b0c6521d76.png)
> ![image](https://user-images.githubusercontent.com/2765208/57508822-391a5a00-7335-11e9-976a-17168677087e.png)
> ![image](https://user-images.githubusercontent.com/2765208/57508842-45061c00-7335-11e9-8716-46ae2d2379db.png)
> ![image](https://user-images.githubusercontent.com/2765208/57508857-4cc5c080-7335-11e9-98ad-68c7c9fd9b93.png)
> 
> 训练过程中得到了 一个 best model : best_model53600_0.03806.h5
> 使用这个模型 在 test-clean 上测试 得到 EER = 7%~10%
> 
> 在训练或者 测试过程中，我遗漏了什么 或者 还有 什么 tricks 的吗？ 期待你的回复，谢谢！
> 
> 再次 感谢您上传如此优质的项目！

请问一下您，“直接用 select_batch 的triplet-loss进行训练,”是怎样怎样训练的？怎样修改运行代码呢

**Comment by izhangy** [comment]
请问“checkpoints / model_17200_0.54980.h5”是运行哪一个文件生成的？我无法得到这个训练模型保存的结果

**Comment by Walleclipse** [comment]
> 请问一下您，“直接用 select_batch 的triplet-loss进行训练,”是怎样怎样训练的？怎样修改运行代码呢

 在 `constants.py `中 设置 `PRE_TRAIN=False`，随后就不会pretrain直接用select_batch 的triplet-loss进行训练

**Comment by Walleclipse** [comment]
> 请问“checkpoints / model_17200_0.54980.h5”是运行哪一个文件生成的？我无法得到这个训练模型保存的结果

这个就是我在运行 train.py 到第17200步的时候产的，随后测试的eer=0.54980。当然每个人训练的时候产生的checkpoint不太一样，所以eer一般情况不等于我的这个checkpoint.
