### ISSUE TITLE
help！！

### ISSUE THREAD

**Issue by tingtingzhezhe** [Walleclipse/Deep_Speaker-speaker_recognition_system#31]
你好！感谢您之前的帮助，想请问您手上有没有一些代码框架注释说明，想向您请求一下！可以邮件发给我么？非常感谢！！！

**Comment by Walleclipse** [comment]
不好意思，我做这个项目时没有注释。
你可以查看 [deep_speaker实验报告.pdf ](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/blob/master/deep_speaker%E5%AE%9E%E9%AA%8C%E6%8A%A5%E5%91%8A.pdf) ，如果有不明白的，你可以在这里提问。
