### ISSUE TITLE
GPU版本

### ISSUE THREAD

**Issue by WenhaoSong** [Walleclipse/Deep_Speaker-speaker_recognition_system#32]
你好，请问这套代码有GPU版本的吗，现在在CPU上跑（渣处理器）出结果很慢~

**Comment by Walleclipse** [comment]
你好，这个代码就是gpu版的。你需要安装tensorflow-gpu和keras。

**Comment by WenhaoSong** [comment]
额 都装了的  但是并没有在GPU上跑~  
我是采用的CUDA8.0可对应版本的Cudnn,TF...
请问你的CUDA,TF,Keras版本是多少啊，

**Comment by Walleclipse** [comment]
CUDA 8.0 应该可以的，你验证一下你是否是tensorflow-gpu版本。如果有tensorflow需要uninstall，重新安装tensorflow-gpu
