### ISSUE TITLE
大佬求救

### ISSUE THREAD

**Issue by bianyuelou** [Walleclipse/Deep_Speaker-speaker_recognition_system#33]
您好，加载pretrain预训练模型 用triplet loss训练时，我尝试了您实验手册的学习率， 只有0.0001收敛 其他都不收啊，可是0.0001我跑了 20万个step 一直下降 没有像论文里面说的 下降后上升 您有遇到这种情况吗？

**Comment by Walleclipse** [comment]
这个没有遇到哎，虽然我实验当中验证集上的 loss是先上升一小段然后再下降，但是eer等metrics是一直下降的，你可以验证一下这些metrics是否一直下降，如果是下降的趋势那应该问题不大。
你用的Adam 优化器么？Adam优化器的学习率=1e-3应该是没有问题的呀。我觉得你设置lr=1e-3可以多跑几个step等一下，看看他是否会下降。

**Comment by bianyuelou** [comment]
谢谢您的回复，使用的adam 请问你的f measure 是像你的实验报告里面的一样85000step 才明显有上升趋势的吗

**Comment by Walleclipse** [comment]
> 谢谢您的回复，使用的adam 请问你的f measure 是像你的实验报告里面的一样85000step 才明显有上升趋势的吗

我实验的时候是这样子的，但是由于随机性不一定每次都这样。
