### ISSUE TITLE
details in english

### ISSUE THREAD

**Issue by aSafarpoor** [Walleclipse/Deep_Speaker-speaker_recognition_system#34]
hi.
 I'm study speech recognitions and your code looks really valuable.
but
please can you share the details in English?
Thanks :)

**Comment by Walleclipse** [comment]
Sorry for the late reply.
I added the experiment details in  [deep_speaker_report.pdf](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/blob/master/deep_speaker_report.pdf)

**Comment by aSafarpoor** [comment]
thank you very  much
