### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by DeepLearning723** [Walleclipse/Deep_Speaker-speaker_recognition_system#36]
您好，感谢您的优质代码，最近我也在学习声纹识别这方面的知识。我想请问您在train.py中给的循环条件是while True，我运行后它就一直在跑，为什么您要用这个条件呢？谢谢指点！

**Comment by Walleclipse** [comment]
你好，
因为我最初实验的时候不清楚需要跑几个epoch，防止过早的结束以至于达不到最优状态，我就设置了一直运行，然后直接通过kill 进程来终止程序。当然你可以把那一句改成有终止条件的，这样就更美观。
`for ep in epoch:
     ***
`

**Comment by DeepLearning723** [comment]
谢谢，祝你学业顺利，生活愉快！
