### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by LittleMaWen** [Walleclipse/Deep_Speaker-speaker_recognition_system#40]
您好，请问运行前是否需要先激活tensorflow环境？然后再运行python train.py?我激活环境运行该文件后，出现以下错误：
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    import select_batch
  File "/home/dcase/mawen/SW/Deep_Speaker-speaker_recognition_system-master/select_batch.py", line 18, in <module>
    from pre_process import data_catalog
  File "/home/dcase/mawen/SW/Deep_Speaker-speaker_recognition_system-master/pre_process.py", line 6, in <module>
    from python_speech_features import fbank, delta
ModuleNotFoundError: No module named 'python_speech_features'
在我conda install python_speech_features后，又出现以下错误：
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python_speech_features

Current channels:

  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/linux-64
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
请问该如何解决？

**Comment by Walleclipse** [comment]
`pip install python_speech_features`
conda 似乎无法安装python_speech_features这个库，需要用 `pip install`

**Comment by LittleMaWen** [comment]
> `pip install python_speech_features`
> conda 似乎无法安装python_speech_features这个库，需要用 `pip insta谢谢

**Comment by LittleMaWen** [comment]
谢谢谢谢~我之前激活tensorflow用的是conda activate tensorflow-gpu这个命令，现在直接source activate tensorflow,然后运行train.py就没有出现这个问题了！感谢！另外，想请问，首先python train.py之后，接下来的步骤是怎样呢？train.py是在训练模型嘛？不好意思，我刚接触，不太懂，烦请回复，谢谢您！
