### ISSUE TITLE
训练完成后，每次测试的结果在变化

### ISSUE THREAD

**Issue by dongzhenguo2016** [Walleclipse/Deep_Speaker-speaker_recognition_system#44]
学长你好！我从train-clean-100选择了5个人的数据。按照训练：测试=4:1的比例划分了训练数据和测试数据。然后我训练了5个人的数据，训练好之后，我再测试这5个人的测试数据。测试和训练都能跑通。
但是我发现了一个问题，同样是这5个人的测试数据，每次测试输出的结果都不同，f-measure、true positive rate、accuracy和eer是在变化的。
我原本以为训练好之后，模型的权重就定了，测试的时候调用固定权重之后的参数去测试，测试结果应该也是不变的才行呀？但是每次测试，结果都不一样。
学长，怎么样才能让测试的结果固定呀？
谢谢学长！刚入门声纹识别这一领域，麻烦学长了

![测试](https://user-images.githubusercontent.com/20853353/63954922-7f4b2300-cab6-11e9-90cb-159fa116ccca.png)

**Comment by Walleclipse** [comment]
你每次测试的语音是一样的么？也就是每一次都得测试那5个人同样的语音。
按理来说，如果是同样的测试数据那么结果应该一样。

**Comment by JuneRen** [comment]
因为在特征提取选择音频时，音频长度大于模型输入长度会选择一个随机点进行切割的

**Comment by LittleMaWen** [comment]
请问为什么我用编号为1-3的人去训练，然后再用编号为4-5的人去测试，得到的结果却是f-measure = 0.9999999999995, true positive rate = 1.0, accuracy = 0.99999999999998, equal error rate = 0.0，这个结果不就代表着测试的人和训练的人是一样的吗？但实际上并不同啊？

**Comment by Walleclipse** [comment]
数据太少了，不能说明问题。还是建议下载完整的[LibriSpeech](http://www.openslr.org/12/)数据再运行程序。
