### ISSUE TITLE
The normalisation of Fbank?

### ISSUE THREAD

**Issue by LeoniusChen** [Walleclipse/Deep_Speaker-speaker_recognition_system#48]
The fbank is normalised at the dimension of feature rather than frame, which is different from the definition. I'm confused with this. Could you tell me why?

**Comment by Walleclipse** [comment]
Sorry, I am not an expert in this field. I do not know which is better.  
I only know, in the field of speech, generally normalize the Fbank in feature dimension. 
You can refer the following discussions:
[How to normalize MFCCs](https://www.kaggle.com/c/freesound-audio-tagging/discussion/54082)
[Effect of MFCC normalization on vector quantization based speaker identification](https://ieeexplore.ieee.org/document/5711789)
[Feature Normalisation for Robust Speech Recognition](https://arxiv.org/pdf/1507.04019.pdf)
