### ISSUE TITLE
请教一下流程

### ISSUE THREAD

**Issue by yy835055664** [Walleclipse/Deep_Speaker-speaker_recognition_system#52]
师兄你好：
        请问复现你这个代码，先进行数据预处理pre_process，然后进行train，在进行test吗？

**Comment by Walleclipse** [comment]
你好，请查看[issue1](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/issues/1)
大概流程如下：
1. 准备数据 .你可以直接用我提供的sample data 或者 下载完整的  [Librispeech](http://www.openslr.org/12/) 数据 或者类似格式的数据。如果你新下载了Librispeech数据或者用了自己的数据需要通过  `pre_process.py` 来预处理数据。（我提供的sample data已经处理好了）
2. 如果你需要预训练那么先运行 `pretraining.py` 然后再运行 `train.py`。 如果你想直接训练，可以直接运行 `train.py`。注意是否pretrain 还需要在` constants.py` 里设置 `PRE_TRAIN `
3. 训练过程当中就会进行测试。当然训练完了后你也可以通过` test_model.py` 进行测试。
4. 画出loss图或者EER随训练变化的题，如下：
```
import constants as c
from utils import plot_loss
loss_file=c.CHECKPOINT_FOLDER+'/losses.txt' # loss file path
plot_loss(loss_file)
```
