### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by yy835055664** [Walleclipse/Deep_Speaker-speaker_recognition_system#53]
学长你好，
        刚才在复现你的代码时，test_model,发现测试的是checkpoints中最后一个model xx.h5文件，请问训练的时候这个文件会自动生成最新的训练model吗？

**Comment by Walleclipse** [comment]
是的，运行 `train.py` 以后每过 `SAVE_PER_EPOCHS `步就会保存 checkpiont 里面.h5文件。默认情况下`SAVE_PER_EPOCHS=200`， 你可以在`constants.py` 里修改 `SAVE_PER_EPOCHS`。并且训练的过程当中就会对每一个checkpoint进行测试，并且输出测试结果。 
你也可以在 `test_model.py` 的146行任意指定你想测试的checkpoint文件名，来测试任意一个checkpoint。
