### ISSUE TITLE
关于“silence_detector.py”文件？ 

### ISSUE THREAD

**Issue by izhangy** [Walleclipse/Deep_Speaker-speaker_recognition_system#54]
wav_fn = '/Users/walle/PycharmProjects/Speech/coding/my_deep_speaker/audio/spk_ver_20180401_20180630_70_3_reseg_test/wav' \
             '/spk_ver_20180401_20180630_70_3_reseg_testZEBRA_KIDS00000_110411652-ZEBRA_KIDS00000_110411652_ff3875f4fb3e5ef4.wav'
请问这个路径里的数据是什么，是干什么的？

**Comment by Walleclipse** [comment]
这个只是我本地电脑上的一个wav文件路径，目的就是测试这个  `class  SilenceDetector`。你可以把这个路径替换成你电脑上的wav文件路径，来测试。这个SilenceDetector的目的是检查一段语音中是否有静音。
