### ISSUE TITLE
关于NUM_FRAMES等参数设置的问题

### ISSUE THREAD

**Issue by ShaofengZou** [Walleclipse/Deep_Speaker-speaker_recognition_system#6]
#### 您好，最近我在研究您的这个deep speaker程序，在自己的笔记本上用CPU跑的，跑train.py的时候会出现资源不够用的情况：
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[96,128,16,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc..
#### 期待您的回复~

**Comment by Walleclipse** [comment]
新年好！
NUM_FRAMES 就是帧数，我选的是160，这相当于是持续1.6s的语音，已经比较短了。如果你设置成32，相当于0.32s，我觉得这个时间太短了。根据一个0.32s的语音去判断说话者是谁，这个是很难的。所以我觉得这个会导致准确度降低。你可以不改变NUM_FRAMES，而是降低BATCH_SIZE 试试，比如 BATCH_SIZE=2.
我在GPU上跑的，实际上不需要60个小时，但是5个小时以上估计是需要的（当然具体看你的数据集，batch大小和计算机配置）。CPU上我没试过，可能会慢很多。

**Comment by ShaofengZou** [comment]
嗯嗯，明白了，非常感谢！
祝新年科研顺利！！

**Comment by Walleclipse** [comment]
不谢！
也祝你一切顺利！
