### ISSUE TITLE
关于使用TIMIT数据集的问题

### ISSUE THREAD

**Issue by ZJG0** [Walleclipse/Deep_Speaker-speaker_recognition_system#60]
您好，我使用`train.py`训练,一直卡在这个地方，是数据的问题吗？
![QQ截图20200313160042](https://user-images.githubusercontent.com/24633447/76601460-efe1fa80-6543-11ea-9744-0306d0a49473.png)

**Comment by Walleclipse** [comment]
应该不是数据的问题，可能就是选择最优喂入数据的 select batch 这一步很慢。你可以改一些参数使其加快或者换成 random_batch， 请查看 [issue 37](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/issues/37) 。

**Comment by ZJG0** [comment]
您好，我已经使用`random_batch.py`训练完模型，但是结果不太理想，我又在这个基础上使用了`select__batch.py`进行训练，但是已经跑了80个小时了，依旧卡在`select`阶段，不知道就是这么慢还是我的数据有问题？

**Comment by sophia-396** [comment]
您好，我使用了checkpoints/model_17200_0.54980.h5的权重做迁移学习，使用了您的网络结构，在原本的CNN模型加了一层softmax层，并且只训练最后一层。用的是TIMIT数据集，结果出现如下
![图片](https://user-images.githubusercontent.com/52533920/78420803-22839c80-7685-11ea-87e4-f97e7961bd18.png)，能否帮忙分析以下是什么问题呢？

**Comment by Walleclipse** [comment]
我不太了解 TIMIT数据集， 但是看这张图似乎，模型对train set过拟合了。没有泛化到 validation set上。我觉得你可以训练所有层，而不只是训练最后一个softmax层。毕竟数据很不一样，训练最后一层可能远远不够迁移到新的数据上。
