### ISSUE TITLE
What is stopping condition in train.py

### ISSUE THREAD

**Issue by RushiKawade** [Walleclipse/Deep_Speaker-speaker_recognition_system#61]
Please explain how to stop infinite loop in train. Py

**Comment by Walleclipse** [comment]
Sorry for the late reply.
If I want to stop the loop, I will kill the training process.  
Besides, I just added a stopping condition in my code. Please check 118~121 lines in `train.py`. You can change the value of `Num_Iter` to determine the stopping condition
