### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'best_checkpoint'

### ISSUE THREAD

**Issue by Chloe-qiuyu** [Walleclipse/Deep_Speaker-speaker_recognition_system#73]
when i run the demo ,the issue happened,if i forgot any step?

**Comment by Walleclipse** [comment]
Hi, 
You can use ONE of the following methods：
1) Specify the checkpoint path of `BEST_CHECKPOINT_FOLDER` in [constants.py](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/blob/master/constants.py).  
 `BEST_CHECKPOINT_FOLDER = 'checkpoints'`.  
My checkpoint was saved in [checkpoints](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/tree/master/checkpoints).
2) In [train.py](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/blob/master/train.py), modify all `c.BEST_CHECKPOINT_FOLDER` to `c.CHECKPOINT_FOLDER`.
