### ISSUE TITLE
Confused with the similarity results 

### ISSUE THREAD

**Issue by fabianoluzbr** [Walleclipse/Deep_Speaker-speaker_recognition_system#76]
Hello guys,

I am using this code [here](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/issues/30) but I have noticed that each time I run the test the result is different and they are very non-deterministic. For example: for the same pair, sometimes the similarity returns 0.7 another time returns 0.10, am I doing something wrong?

PS: I am using the model with 74 speaker and 30 seconds of speech for each one.

best

**Comment by Walleclipse** [comment]
Hi,
I think the main reason is the random clip in `def clipped_autio` in the [code](https://github.com/Walleclipse/Deep_Speaker-speaker_recognition_system/issues/30). The audio was random clipping before feeding into the model if the audio is too long.  
You can modify the `def clipped_autio` to a deterministic clip. (clip the deterministic middle frames of the long audio, or clip different parts of the long audio then average the different results).  
Or fixed the random seed during running the code, according to [reproducible-results-neural-networks-keras](https://machinelearningmastery.com/reproducible-results-neural-networks-keras/).
